# @package _global_
engine_name: extract_features
config:
  DATA:
    NUM_DATALOADER_WORKERS: 5
    TRAIN:
      DATA_SOURCES: [ disk_folder ]
      DATASET_NAMES: [ imagenet1k_folder ]
      LABEL_SOURCES: [disk_folder]
      DATA_PATHS: [ "./data/imagenet256/train" ]
      LABEL_TYPE: "standard"
      BATCHSIZE_PER_REPLICA: 128
      TRANSFORMS:
        - name: Resize
          size: 256
        - name: CenterCrop
          size: 224
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      MMAP_MODE: False
      COPY_TO_LOCAL_DISK: False
      COPY_DESTINATION_DIR: /tmp/imagenet1k/
      ENABLE_QUEUE_DATASET: False
    TEST:
      DATA_SOURCES: [ disk_folder ]
      DATASET_NAMES: [ imagenet1k_folder ]
      DATA_PATHS: [ "./data/imagenet256/val" ]
      LABEL_TYPE: "standard"
      LABEL_SOURCES: [disk_folder]
      BATCHSIZE_PER_REPLICA: 128
      TRANSFORMS:
        - name: Resize
          size: 256
        - name: CenterCrop
          size: 224
        - name: ToTensor
        - name: Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      MMAP_MODE: False
      COPY_TO_LOCAL_DISK: False
      COPY_DESTINATION_DIR: /tmp/imagenet1k/
      ENABLE_QUEUE_DATASET: False
  MODEL:
    TRUNK:
      NAME: resnet
      RESNETS:
        DEPTH: 50
    WEIGHTS_INIT:
      PARAMS_FILE: "specify the model weights"
      STATE_DICT_KEY_NAME: classy_state_dict
    FEATURE_EVAL_SETTINGS:
      EVAL_MODE_ON: True
      FREEZE_TRUNK_ONLY: True
      EXTRACT_TRUNK_FEATURES_ONLY: True
      SHOULD_FLATTEN_FEATS: False
    AMP_PARAMS:
      USE_AMP: True
      AMP_TYPE: pytorch
  EXTRACT_FEATURES:
    # Path where to save the features: if empty, the checkpoint folder
    # will be used as location where to save the features
    OUTPUT_DIR: ""
    CHUNK_THRESHOLD: 20000
    MAP_FEATURES_TO_IMG_NAME: False

  DISTRIBUTED:
    NUM_NODES: 1
    NUM_PROC_PER_NODE: 1
  MACHINE:
    DEVICE: gpu

  SLURM:
    NAME: "feature_extract"
    MEM_GB: 32 #  4 (gpu per node) * 32
    USE_SLURM: True
    TIME_HOURS: 5

